name = "post-composer"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "static"

[[kv_namespaces]]
binding = "DRAFTS_KV"
id = "fa165954221a4ac69dc2655150a8a3f9"
